name: Apply PARDOK XML Diff to DB

on:
  push: main

jobs:
  pardok-xml-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: preparation
        run: |
          npm ci && 
          curl https://www.parlament-berlin.de/opendata/pardok-wp19.xml > pardok-wp19.xml &&
          [[ -s pardok-wp19.xml ]] || (echo "PARDO XML file is empty" && exit 1)
      - name: dry run # Dry run exits with error code when there are Vorgangs that will be deleted
        run: npx tsx index.ts -f pardok-wp19.xml -d postgres://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }} --update-db --dry-run
      - name: apply diff without deletion
        run: |
          "${{ github.event.client_payload.dry_run }}" == 'false' && "${{ github.event.client_payload.allow_deletion }}" == 'false' && 
          npx tsx index.ts -f pardok-wp19.xml -d postgres://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }} --update-db
      - name: apply diff with deletion
        run: |
          "${{ github.event.client_payload.dry_run }}" == 'false' && "${{ github.event.client_payload.allow_deletion }}" == 'true' &&
          npx tsx index.ts -f pardok-wp19.xml -d postgres://${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }} --update-db --allow-deletion
