name: Apply PARDOK XML Diff to DB

on:
  push:
    branches:
      - 'feat/diff-ci' # for testing, remove later
  workflow_dispatch: {}
  repository_dispatch:
    # This action can be triggered via Github API webook 
    # (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)
    types: [pardok_diff_apply]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Apply PARDOK XML Diff
        run: |
        npm ci
        curl https://www.parlament-berlin.de/opendata/pardok-wp19.xml > pardok-wp19.xml
        npx tsx index.ts -f pardok-wp19.xml -d postgres://${{ vars.DB_USER }}:${{ vars.DB_PASSWORD }}@{{ vars.DB_HOST }}:${{ vars.DB_PORT }}/${{ vars.DB_NAME }} --update-db
